### ISSUE TITLE
The Resolve feature

### ISSUE THREAD

**Issue by MattR88** [jamieshepherd/tygr#36]
Would it be worth considering functionality for two, or even three stage resolution. For example, if the developer working on the issue marks the issue as resolved, this will then need to be QA’d and then marked as resolved. Once with the client, they will need a way to signal their sign off. While this could be done with comments, it would be simpler in viewing terms to simply review the list of issues and their resolved/active status.

**Comment by jamieshepherd** [comment]
At the moment, once an issue has been "resolved" by the developer, it will automatically become assigned to the client, which they will be able to see in their "assigned to me" list. They are then able to review the change, and if happy that it's been implemented, "close" the issue. There are currently 5 status, new, assigned, awaiting client, resolved, and closed. Does this answer your question or are you looking for a feature implementation here?

**Comment by MattR88** [comment]
I was thinking along the lines of not wanting to have issues trickling back to the client piecemeal, as some clients would probably immediately try to check them before the latest version had been uploaded to the review area. Ideally, I think the developer working on the issue fixes needs to be able to resolve the issue without it automatically being assigned back to the client to enable a bulk assigning of cases/issues back to the client once the QA had been done. Also anyone doing the QA would need to see that all of the cases/issues had been completed and were ready for review, on the logs at the moment, we have the three columns to facilitate this. Rather than just having a resolved status, perhaps having three, 'Resolved' 'Reviewed' 'Completed' in addition to the 'New', 'Assigned' and 'Awaiting Client'. The first two to be internal statuses, and the third to be the one that assigns the case back to the client for their sign off. The first three would need to be independent of the second three, so a case could be 'Completed' & 'Awaiting Client'. Happy to chat through if this isn't making sense!

**Comment by jamieshepherd** [comment]
No that makes perfect sense, I'll have a think and chat with Alan about this, as I want to keep it as simple as possible without adding too many possible issue states. It's also possible that we could just have a QA group to assign the issue to. Once a developer has finished instead of resolving he can just assign to QA (similar to how Kineo's Trac system works if you've used that). Then at QA it can be batch assigned to the client. I'll definitely have a think but wan't to limit the complexity for Sponge as well as the client. In an ideal world each time it goes to each department they would just do their changes and hit "complete" and it would go off to wherever it needs to. Perhaps we should make all of the issues locked until we're happy they're all done and just have a generic "amends completed" button for project managers. Good points, thanks again for your feedback!

**Comment by jamieshepherd** [comment]
Alan had the idea of locking projects until they were "finished" as far as we are concerned. For example, a client submits their changes, and when they are ready to be worked on the PM will lock the version (and all of the changes associated with it) so the devs can work on them. During this time clients won't be able to close the issues until it is "unlocked" and a new version has been published (for which new issues will be logged against). Still need to think more into a concrete implementation of this, but I feel like this might be a more elegant way to approach it.

**Comment by jamieshepherd** [comment]
For the moment we're going to see how clients use it, if they end up getting ahead of themselves we'll open a new issue and implement it, but for now we'll see how it goes.
